### ISSUE TITLE
Export Rankings

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.vis.lineup.demos#10]
We should be able to export rankings to a csv file. Instead of the raw input data, we would write the weighted scores. 

An issues arises if we have multiple simultaneous visible rankings. We could ask the user to choose one.

**Comment by sgratzl** [comment]
a simple version is included.

I handle the multiple snapshots by just adding another table below the first one containing all the columns, headers,...

so it is a simple cut&paste operation is Excel to restore the snapshots again
