### ISSUE TITLE
data loading on Mac appears to be broken

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.vis.lineup.demos#2]
comming from Caleydo/org.caleydo.view.lineup#1

When I click on the "Load Data" menu item it gets highlighted, but nothing else happens.

![screen shot 2013-08-15 at 9 32 54 pm](https://f.cloud.github.com/assets/1216518/973004/fe4ba224-0613-11e3-9cf3-30ab306a582d.png)

**Comment by sgratzl** [comment]
I don't know why but please test to click twice on the button. 

I wrapped the Load Data button in a File menu, maybe that helps. 

In addition it should now be automatically build too during the super.project

**Comment by ngehlenborg** [comment]
It works with the new File menu. Clicking twice in the old version (which was from the LineUp website, btw) just deselects the selected menu item.
