### ISSUE TITLE
Improve UI for importing floats 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.vis.lineup.demos#5]
Currently you have to remove the values from Mapping Min and Mapping Max to auto-infer min and max.

![mapping_setting](https://f.cloud.github.com/assets/2039375/1181872/c3f13a2c-220f-11e3-9b43-2bbfbbbb3bed.png)

It would be better to have a radio that says "Infer min and max from your data", selected by default, and only provide the option of switching to "Specify Min and Max". 

I'm not even sure if we need to define Min and Max on import at all. Isn't that easy to do in the GUI later?

**Comment by sgratzl** [comment]
> I'm not even sure if we need to define Min and Max on import at all. Isn't that easy to do in the GUI later?

if you have percentages and your values aren't in the range 0..1 you probably want to fix it in that range

**Comment by sgratzl** [comment]
by default it will be Inferred + add a hint note to the properties editor
