### ISSUE TITLE
Find and load Soccer data

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.vis.lineup.demos#7]

**Comment by sgratzl** [comment]
http://www.rsssf.com/

http://www.researchgate.net/post/Can_anyone_suggest_to_me_a_public_soccer_database_I_want_some_data_to_try_to_find_out_a_Brazilian_dream-team_with_a_multi-criteria_algorithm

**Comment by mstreit** [comment]
http://www.transfermarkt.com/
http://www.transfermarkt.com/en/wettbewerbe/jahreswertung/wettbewerbe.html
http://www.transfermarkt.com/en/spieler/goldenerschuh/basics.html
http://www.transfermarkt.com/en/default/basics/marktwert-aenderung.html

The database seems to be one of the most comprehensive ones. For players, for instance, many different attributes are available. However, I didn't yet found a way to download the raw data.

**Comment by mstreit** [comment]
As the data is provided as HTML tables, it shouldn't be too hard to load the data though.

**Comment by sgratzl** [comment]
> The database seems to be one of the most comprehensive ones. For players, for instance, many different attributes are available. However, I didn't yet found a way to download the raw data.

is it allowed to use the data?

**Comment by mstreit** [comment]
We would need to ask them. See:
http://www.transfermarkt.at/de/information/nutzungsbedingungen/intern.html
